### ISSUE TITLE
Remove WordPress REST API – OAuth 1.0a Server dependency

### ISSUE THREAD

**Issue by jsiren** [OPMerchantServices/op-kassa-for-woocommerce#22]
**Is your feature request related to a problem? Please describe.**

The WordPress REST API – OAuth 1.0a Server plugin is old and not supported on current WordPress/WooCommerce versions. It has been tested up to 4.7-alpha, whereas OP Kassa requires 4.9 or newer. Also, WordPress REST API – OAuth 1.0a Server conflicts with WooCommerce Shipping & Tax (which is still called WooCommerce Services in OP Kassa). 

**Describe the solution you'd like**

Replace said dependency with something that is actively supported and works with current WordPress and WooCommerce.

**Designs**

Not applicable, I am not familiar enough with how this dependency is used.

**Describe alternatives you've considered**

Not applicable, since OP Kassa cannot be activated without WordPress REST API – OAuth 1.0a Server.

**Additional context**

**Comment by loueranta** [comment]
@jsiren The need for separate OAuth plugin will be removed tomorrow when we release 2.0.0 and update the integration service
